// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtfx3yeU8xAZOlrKPIfDnDLNNaVjRsJno',
    appId: '1:1082576997079:web:4989396f5960edbd24be92',
    messagingSenderId: '1082576997079',
    projectId: 'dailyenglish-12c3d',
    authDomain: 'dailyenglish-12c3d.firebaseapp.com',
    storageBucket: 'dailyenglish-12c3d.appspot.com',
    measurementId: 'G-QE10TG1HWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8tDOIIUhZhRhYshESfHBTPjEEOxRNPRo',
    appId: '1:1082576997079:android:01a7472966ea82d324be92',
    messagingSenderId: '1082576997079',
    projectId: 'dailyenglish-12c3d',
    storageBucket: 'dailyenglish-12c3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOZ5iKafoNIGLrtg_uBGag8e-5xJXQNHc',
    appId: '1:1082576997079:ios:f17f9f33ec47011624be92',
    messagingSenderId: '1082576997079',
    projectId: 'dailyenglish-12c3d',
    storageBucket: 'dailyenglish-12c3d.appspot.com',
    iosBundleId: 'com.example.dailyenglishapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOZ5iKafoNIGLrtg_uBGag8e-5xJXQNHc',
    appId: '1:1082576997079:ios:98f7f47721abcf2c24be92',
    messagingSenderId: '1082576997079',
    projectId: 'dailyenglish-12c3d',
    storageBucket: 'dailyenglish-12c3d.appspot.com',
    iosBundleId: 'com.example.dailyenglishapp.RunnerTests',
  );
}
