// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh9ThyE09PHM2OHP9jDG0jBnpV4UrEvL0',
    appId: '1:675237433524:web:774a508e03bd0d7b7b07e1',
    messagingSenderId: '675237433524',
    projectId: 'capalocaproject-182eb',
    authDomain: 'capalocaproject-182eb.firebaseapp.com',
    storageBucket: 'capalocaproject-182eb.appspot.com',
    measurementId: 'G-1BBZENHN14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUG_wE7aibOU-8BPVO7vehjleRhd1N-U',
    appId: '1:675237433524:android:56703b64a31a9a347b07e1',
    messagingSenderId: '675237433524',
    projectId: 'capalocaproject-182eb',
    storageBucket: 'capalocaproject-182eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2DO5VNCRUbmUesEe4ia-Pd1yWKDNO-Vc',
    appId: '1:675237433524:ios:36da2e87644e58a57b07e1',
    messagingSenderId: '675237433524',
    projectId: 'capalocaproject-182eb',
    storageBucket: 'capalocaproject-182eb.appspot.com',
    iosClientId:
        '675237433524-qj8l5u4e5nk2v5poqidgsnf9p3ltuvnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2DO5VNCRUbmUesEe4ia-Pd1yWKDNO-Vc',
    appId: '1:675237433524:ios:af6d29c555810ca57b07e1',
    messagingSenderId: '675237433524',
    projectId: 'capalocaproject-182eb',
    storageBucket: 'capalocaproject-182eb.appspot.com',
    iosClientId:
        '675237433524-huba0tt8k35a1sk33i5vrc8gj513o5b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainApp.RunnerTests',
  );
}
